services:
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-microservices-project:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres-data-microservices-project:
     driver: local

