spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices_db
    username: microservices
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
